### ISSUE TITLE
Statistics filter for "Error" does not work

### ISSUE THREAD

**Issue by lesley-w** [PerplexDigital/PerplexMail-for-Umbraco#10]
Client has raised an issue where they are trying to filter the email statistics for errors, but all records are being returned.

The problem seems to be this line in SQL_QUERY_GET_STATISTICS

"	(@status = 1 AND result.[exception] IS NOT NULL) "

When an email is logged, if there are no errors, the exception field is set to an empty string, but the statistics query is checking for NULL.

I believe the check should be
"	(@status = 1 AND result.[exception] IS NOT NULL AND result.[exception] <> '') "

Can you confirm that my assumption is correct and that it's not something we have done that has broken things?

Thanks

**Comment by lesley-w** [comment]
Would also require a fix to the "Sent" filter as this is currently broken as well:

(@status = 0 AND v.[viewed] IS NULL AND c.[clicked] IS NULL AND w.[webversion] IS NULL AND ISNULL(result.[exception],'') = '')

**Comment by PerplexWouter** [comment]
Hi @lesley-w,

> I believe the check should be
> " (@status = 1 AND result.[exception] IS NOT NULL AND result.[exception] <> '') "

The Mail package shouldn't really consider an empty string as an error, so checking for an empty string to filter it out sounds like a good solution. I don't forsee anything going wrong with this change.

> Would also require a fix to the "Sent" filter as this is currently broken as well:
> (@status = 0 AND v.[viewed] IS NULL AND c.[clicked] IS NULL AND w.[webversion] IS NULL AND ISNULL(result.[exception],'') = '')

This change should be fine as well! If you want to you can send it in as a PR and I can merge it in.

**Comment by PerplexWouter** [comment]
@lesley-w I've pushed the latest build to the master branch, including the new version of the assembly (which you can download) at output/PerplexMail.dll, or you can pull the master branch and make a release build yourself. I presume everything should work as expected from here.

If you run into any more issues, feel free to re-open this issue or start a new one.
