### ISSUE TITLE
Checkbox validation

### ISSUE THREAD

**Issue by JakeDK** [PerplexDigital/PerplexMail-for-Umbraco#3]
Great plug-in! But is it possible to validate a checkbox? eg. 
{if [#somecheckbox#] = True } Yes {/if}

**Comment by JeffreyPerplex** [comment]
Hi Jake,

Thank you! 

It should be possible but it's based on string comparison so it should look like 
{if [#somecheckbox#] = 'true' } Yes {/if}
or like {if [#somecheckbox#] = '1' } Yes {/if}

The easiest way is to just put the value [#somecheckbox#] in your testmail and check out which value it gets. After that you know what the value will be & can use it to compare.
