### ISSUE TITLE
database fields alternativeView and attachment are not encrypted

### ISSUE THREAD

**Issue by sanderlanghorstredhotminute** [PerplexDigital/PerplexMail-for-Umbraco#6]
Hi,

A set of database fields in perplexMailLog is getting Encrypted for security, which is a good thing.
However, the fields alternativeView and attachment are not getting encrypted, leaving the body of the email, including personal data, unencrypted.

Kind regards,

Sander

**Comment by PerplexWouter** [comment]
We will keep this in mind for possible newer versions of the package.
